// 50 sample listings for seeding the database
const sampleListings = [
  {
    title: "Cozy Mountain Cabin",
    description: "A beautiful cabin in the mountains, perfect for a weekend getaway.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 120,
    location: "Manali",
    country: "India",
  },
  {
    title: "Urban Apartment",
    description: "Modern apartment in the heart of the city with all amenities.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    price: 200,
  location: "Mumbai",
  country: "India",
  },
  {
    title: "Beachside Villa",
    description: "Luxurious villa with a private beach and pool.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 350,
  location: "Goa",
  country: "India",
  },
  {
    title: "Desert Retreat",
    description: "Experience tranquility in this desert oasis.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    price: 180,
  location: "Jaisalmer",
  country: "India",
  },
  {
    title: "Lake House",
    description: "Charming house with a stunning lake view.",
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e",
    price: 250,
  location: "Nainital",
  country: "India",
  },
  {
    title: "Forest Bungalow",
    description: "Secluded bungalow surrounded by lush forest.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 160,
  location: "Coorg",
  country: "India",
  },
  {
    title: "Hilltop Cottage",
    description: "Cottage with panoramic hill views and fresh air.",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    price: 140,
  location: "Ooty",
  country: "India",
  },
  {
    title: "City Loft",
    description: "Trendy loft in the city center, close to nightlife.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    price: 220,
  location: "Bangalore",
  country: "India",
  },
  {
    title: "Riverside Homestay",
    description: "Peaceful homestay by the river, ideal for families.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    price: 130,
  location: "Rishikesh",
  country: "India",
  },
  {
    title: "Luxury Penthouse",
    description: "Penthouse with skyline views and private terrace.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 500,
  location: "Delhi",
  country: "India",
  },
  {
    title: "Countryside Farmhouse",
    description: "Spacious farmhouse with organic gardens.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    price: 170,
  location: "Punjab",
  country: "India",
  },
  {
    title: "Snowy Chalet",
    description: "Chalet with fireplace and snowy mountain views.",
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e",
    price: 300,
  location: "Shimla",
  country: "India",
  },
  {
    title: "Historic Haveli",
    description: "Stay in a restored haveli with royal charm.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 210,
  location: "Jaipur",
  country: "India",
  },
  {
    title: "Jungle Treehouse",
    description: "Unique treehouse experience in the jungle.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 190,
  location: "Kerala",
  country: "India",
  },
  {
    title: "Island Resort Room",
    description: "Room in a luxury island resort with all facilities.",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    price: 400,
  location: "Andaman",
  country: "India",
  },
  {
    title: "Budget Hostel",
    description: "Affordable hostel for backpackers and solo travelers.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    price: 30,
  location: "Varanasi",
  country: "India",
  },
  {
    title: "Tea Estate Cottage",
    description: "Cottage in the middle of a tea estate.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    price: 110,
  location: "Darjeeling",
  country: "India",
  },
  {
    title: "Palace Suite",
    description: "Live like royalty in a palace suite.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 600,
  location: "Udaipur",
  country: "India",
  },
  {
    title: "Eco Bamboo Hut",
    description: "Eco-friendly bamboo hut with natural surroundings.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    price: 90,
  location: "Meghalaya",
  country: "India",
  },
  {
    title: "Luxury Houseboat",
    description: "Houseboat stay with all modern amenities.",
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e",
    price: 320,
  location: "Alleppey",
  country: "India",
  },
  {
    title: "Mountain View Room",
    description: "Room with breathtaking mountain views.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 150,
  location: "Leh",
  country: "India",
  },
  {
    title: "Artistic Studio",
    description: "Studio apartment with artistic decor.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 100,
  location: "Pune",
  country: "India",
  },
  {
    title: "Colonial Mansion",
    description: "Stay in a grand colonial mansion.",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    price: 450,
  location: "Kolkata",
  country: "India",
  },
  {
    title: "Yoga Retreat",
    description: "Peaceful retreat for yoga and meditation.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    price: 200,
  location: "Rishikesh",
  country: "India",
  },
  {
    title: "Boutique Hotel Room",
    description: "Designer room in a boutique hotel.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    price: 270,
  location: "Chennai",
  country: "India",
  },
  {
    title: "Safari Camp",
    description: "Luxury tented camp for safari adventures.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 350,
  location: "Ranthambore",
  country: "India",
  },
  {
    title: "Riverfront Villa",
    description: "Villa with private river access.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    price: 380,
  location: "Haridwar",
  country: "India",
  },
  {
    title: "Minimalist Flat",
    description: "Minimalist flat with modern interiors.",
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e",
    price: 160,
  location: "Ahmedabad",
  country: "India",
  },
  {
    title: "Vintage Guesthouse",
    description: "Charming guesthouse with vintage decor.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 80,
  location: "Lucknow",
  country: "India",
  },
  {
    title: "Luxury Tent",
    description: "Glamorous tent stay with all comforts.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 210,
  location: "Pushkar",
  country: "India",
  },
  {
    title: "Seaside Cottage",
    description: "Cottage right on the beach.",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    price: 260,
  location: "Pondicherry",
  country: "India",
  },
  {
    title: "Modern Studio",
    description: "Compact studio with all essentials.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    price: 90,
  location: "Hyderabad",
  country: "India",
  },
  {
    title: "Mountain Lodge",
    description: "Lodge with adventure activities nearby.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    price: 170,
  location: "Mussoorie",
  country: "India",
  },
  {
    title: "Luxury Resort Room",
    description: "Room in a 5-star luxury resort.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 420,
  location: "Agra",
  country: "India",
  },
  {
    title: "Rustic Cabin",
    description: "Rustic cabin with wood interiors.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    price: 110,
  location: "Kodaikanal",
  country: "India",
  },
  {
    title: "City Center Suite",
    description: "Suite in the heart of the city.",
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e",
    price: 310,
  location: "Surat",
  country: "India",
  },
  {
    title: "Garden Villa",
    description: "Villa with a private garden.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 230,
  location: "Bhopal",
  country: "India",
  },
  {
    title: "Traditional Cottage",
    description: "Traditional cottage with local architecture.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 120,
  location: "Munnar",
  country: "India",
  },
  {
    title: "Luxury Spa Retreat",
    description: "Retreat with luxury spa facilities.",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    price: 480,
  location: "Kerala",
  country: "India",
  },
  {
    title: "Mountain Camp",
    description: "Camp in the mountains for adventure seekers.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    price: 70,
  location: "Sikkim",
  country: "India",
  },
  {
    title: "Luxury Heritage Room",
    description: "Room in a heritage property with antique decor.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    price: 390,
  location: "Jodhpur",
  country: "India",
  },
  {
    title: "Eco Tree Lodge",
    description: "Eco-friendly lodge built on trees.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 210,
  location: "Wayanad",
  country: "India",
  },
  {
    title: "River Camp",
    description: "Camp by the river with bonfire nights.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    price: 60,
  location: "Ranikhet",
  country: "India",
  },
  {
    title: "Luxury Lake Resort",
    description: "Resort on the lake with water sports.",
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e",
    price: 410,
  location: "Udaipur",
  country: "India",
  },
  {
    title: "Budget Guest Room",
    description: "Simple guest room for budget travelers.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 40,
  location: "Patna",
  country: "India",
  },
  {
    title: "Luxury Mountain Suite",
    description: "Suite with luxury amenities and mountain views.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 520,
  location: "Manali",
  country: "India",
  },
  {
    title: "Artist's Loft",
    description: "Loft with creative vibes and art supplies.",
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    price: 180,
  location: "Goa",
  country: "India",
  },
  {
    title: "Jungle Camp",
    description: "Camp in the jungle with guided tours.",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    price: 80,
  location: "Kanha",
  country: "India",
  },
  {
    title: "Luxury Island Villa",
    description: "Private villa on an island with sea views.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    price: 700,
  location: "Lakshadweep",
  country: "India",
  },
];

module.exports = { data: sampleListings };
